config/routes.rb
Rails.application.routes.draw do
  # get 'profile', to "form#profile_get"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  post '/home/webhook', to: 'home#webhook'

  # QRコード読み取り後のLINEログインページ
  get '/login', to: "forms#login"
  get '/line_login', to: "forms#line_login"
  get 'line_login_api/callback', to: 'forms#callback'

  # フォーム表示、登録
  get 'profile', to: "forms#profile"
  post 'forms/create'
  get 'success', to: "forms#create_success"

  get '/home/test', to: 'home#test'
  get '/home/line_bot_send_push_message', to: 'home#line_bot_send_push_message'
  post '/groups/:event_id', to: 'groups#create'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def login
    @event_id = params[:event_id]
    render 'forms/line_login'
  end

  def line_login
        # CSRF対策用の固有な英数字の文字列
    # ログインセッションごとにWebアプリでランダムに生成する
    session[:state] = SecureRandom.urlsafe_base64

    # ユーザーに認証と認可を要求する
    # https://developers.line.biz/ja/docs/line-login/integrate-line-login/#making-an-authorization-request

    base_authorization_url = 'https://access.line.me/oauth2/v2.1/authorize'
    response_type = 'code'
    client_id = '2001492321' #本番環境では環境変数などに保管する
    redirect_uri = CGI.escape(line_login_api_callback_url)
    state = session[:state]
    scope = 'profile%20openid' #ユーザーに付与を依頼する権限


    authorization_url = "#{base_authorization_url}?response_type=#{response_type}&client_id=#{client_id}&redirect_uri=#{redirect_uri}&state=#{state}&scope=#{scope}"

    redirect_to authorization_url, allow_other_host: true
  end

  def callback

    # CSRF対策のトークンが一致する場合のみ、ログイン処理を続ける
    if params[:state] == session[:state]

      line_id = get_line_user_id(params[:code])
      user = User.find_or_initialize_by(line_id: line_id)


      user.event_id = Event.first.id
      user.icon_id = Icon.where( 'id >= ?', rand(Icon.count) + 1 ).first.id
      user.name1 = "名無しの大田区トラベラー"
      user.name2 = "スシコラ使い"


      if user.save
        session[:user_id] = user.id
        redirect_to profile_path, notice: 'ログインしました'
      else
        redirect_to profile_path, notice: 'ログインに失敗しました'
      end

    else
      redirect_to root_path, notice: '不正なアクセスです'
    end

  end

  def profile
    # ユーザーが見つからなかったら仮でユーザーを作成する
    @user = User.find_by(id: session[:user_id]) || Event.first.users.build(line_id: "line_id", icon_id: Icon.second.id)
    @icon = @user.icon

    render 'forms/profile'
  end

  def create
    @user = User.find_by(line_id: user_params[:line_id]) || User.first

    # TODO: アイコンのURLをセットする
    
    if @user.update(user_params)
      redirect_to success_path
    else
      render 'forms/profile'
    end
  end

  def create_success
    render 'forms/create_success'
  end

  private

  def get_line_user_id(code)

    # ユーザーのIDトークンからプロフィール情報（ユーザーID）を取得する
    # https://developers.line.biz/ja/docs/line-login/verify-id-token/

    line_user_id_token = get_line_user_id_token(code)

    if line_user_id_token.present?

      url = 'https://api.line.me/oauth2/v2.1/verify'
      options = {
        body: {
          id_token: line_user_id_token,
          client_id: '2001492321' # 本番環境では環境変数などに保管
        }
      }

      response = Typhoeus::Request.post(url, options)

      if response.code == 200
        JSON.parse(response.body)['sub']
      else
        nil
      end
    
    else
      nil
    end

  end

  def get_line_user_id_token(code)

    # ユーザーのアクセストークン（IDトークン）を取得する
    # https://developers.line.biz/ja/reference/line-login/#issue-access-token

    url = 'https://api.line.me/oauth2/v2.1/token'
    redirect_uri = line_login_api_callback_url

    options = {
      headers: {
        'Content-Type' => 'application/x-www-form-urlencoded'
      },
      body: {
        grant_type: 'authorization_code',
        code: code,
        redirect_uri: redirect_uri,
        client_id: '2001492321', # 本番環境では環境変数などに保管
        client_secret: 'faed1b611cccd4f4991e28632ba1b540' # 本番環境では環境変数などに保管
      }
    }
    response = Typhoeus::Request.post(url, options)

    if response.code == 200
      JSON.parse(response.body)['id_token'] # ユーザー情報を含むJSONウェブトークン（JWT）
    else
      nil
    end
  end


  def user_params
    params.require(:user).permit(:name1, :name2, :profile, :from, :to, :line_id, :event_id, :line_id)
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/create.html.erb
<h1>Forms#create</h1>
<p>Find me in app/views/forms/create.html.erb</p>

app/views/forms/create_success.html.erb
<div class="container">
    <p>Nomotabiへのご参加ありがとうございます😆</p>
    <p>ただいま、Nomotabiがあなたへピッタリな仲間を探しています。</p>
    <p>LINEでメッセージが届くので、今しばらくお待ちください。</p>
</div>
<style>

body {
  background: #dfdfdf;
}

.container {
  width: 100%;
  height: 100%;
  padding: 0 16px;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
</style>

app/views/forms/line_login.html.erb
<%# TODO: ラインログインを行う %>
<div class="line-login">
    <%= link_to 'LINEでログイン', line_login_path, class: 'line-login-button' %>
</div>


<style>
  .line-login {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh; /* Center the button vertically */
}

.line-login-button {
  background-color: #00c300; /* LINEの緑色 */
  color: white;
  padding: 10px 20px;
  border-radius: 5px; /* 角を丸くする */
  text-decoration: none;
  font-weight: bold;
  display: inline-block;
  transition: background-color 0.3s;
}

.line-login-button:hover {
  background-color: #009900; /* 濃い緑色 */
}
</style>

app/views/forms/profile.html.erb
<div class="profile-container">
<h1>Welocome to Nomotabi 🎉</h1>
<p>大田区の魅力を発見する旅へ出掛けましょう！</p>
<p>大田区の魅力をする発見する旅へNomotabiがご案内します</p>
    <%= form_with model: @user, url: forms_create_path, method: :post, local: true do |form| %>
      <div>
        <%# <%= form.image :icon_url, value: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg" %>
        <div class="image">
          <%= image_tag @icon.image_url, size: "150x150" %>
        </div>
      </div>
      <div class="field">
        <%= form.label :name1, 'ニックネーム' %>
        <%= form.text_field :name1, value: @user.name1, required: true %>
      </div>
      <div class="field">
        <%= form.label :profile, '自己紹介' %>
        <%= form.text_area :profile, required: true %>
      </div>
      <div>
        <%= form.label :profile, 'どこへ行きたいか？' %><br>
        <select name="example">
<option value="サンプル1">和食</option>
<option value="サンプル2">中華</option>
<option value="サンプル3">ラーメン</option>
<option value="サンプル3">焼き肉</option>
</select>
      <div>
        <%= form.label :profile, '性格' %></br>
        <select name="example">
<option value="サンプル1">内向的</option>
<option value="サンプル2">外交的</option>
<option value="サンプル2">おしゃべりが好き</option>
<option value="サンプル2">ゆっくり飲みたい</option>
<option value="サンプル2">たくさん飲みたい</option>
</select>
      </div>
            <div>
        <%= form.label :profile, '話したいこと' %></br>
        <select name="example">
<option value="サンプル1">自分の研究のことを話したい</option>
<option value="サンプル3">キャリアのことを話したい</option>
<option value="サンプル3">趣味のことを話したい</option>
<option value="サンプル2">人の話が聞きたい</option>
</select>
      <div class="field">
        <%= form.label :from, '参加可能時間' %><br>
        <%= form.time_select :from, {default: Date.today + 19.hour} %>
        <%= form.time_select :to, {default: Date.today + 21.hour}  %>
      </div>
      <div>
        <%= form.hidden_field :line_id, value: @user.line_id %>
      </div>
      <div>
        <%= form.hidden_field :event_id, value: @user.event_id %>
      </div>
      <div style="margin-top: 20px;">
        <%= form.submit 'Nomotabiへ参加する👋' %>
      </div>
    <% end %>
	</form>
</div>

<!-- This is not part of Pen -->
<a class="me" href="https://codepen.io/uzcho_/pens/popular/?grid_type=list" target="_blank" style="color:#000"></a>
</div>

<style>
/* @import url('https://fonts.googleapis.com/css?family=Saira+Semi+Condensed&display=swap'); */

* {
  transition: all .5s ease;
  font-family: 'Saira Semi Condensed', sans-serif;
}

body {
  background: #dfdfdf;
}

.container {
  width: 100%;
  height: 100%;
  padding: 0 16px;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
    display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
}

form {
  width: 400px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

form div, form label, form input, form textarea {
  width: 100%;
}

.field:nth-of-type(2) {
  margin: 16px 0;
}

label, input, textarea {
  padding: 8px;
}

label, [placeholder] {
  color: #555;
}

label i {
  margin: 0 10px 0 0;
}

.field:focus-within label {
  color: #000;
  letter-spacing: 2px;
}

input, textarea {
  background: rgba(255, 255, 255, .5);
  border: none;
  border-radius: 4px;
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, .1);
}

input:focus, textarea:focus {
  background: rgba(255, 255, 255, 1);
  box-shadow: none;
}

textarea {
  resize: none;
}

textarea::-webkit-scrollbar {
  width: 0;
}

button {
  background: #2f4ad0;
  padding: 8px 16px;
  margin: 16px 0 50px 0;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, .1);
}

button:hover {
  letter-spacing: 2px;
  box-shadow: none;
}

.social-media {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
}

.social-media:not(:first-child) {
  font-size: 14px;
}

.social-media span {
  font-size: 16px;
}

.social-media span .fas {
  margin: 0 0 0 10px;
}

.social-media a {
  color: #000;
  font-size: 20px;
}

.image {
  display: flex;
  justify-content: center;
  align-items: center;
}

@media (max-width: 425px) {
  form {
    width: 70%;
  }
}


</style>